# apache_install.yml
---
- name: Install and configure Apache
  hosts: gsi_machine
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Update ports configuration
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8081'

    - name: Update default virtual host
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^\s*<VirtualHost \*:80>'
        line: '<VirtualHost *:8081>'

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
